Implement chat messages, mtproto typings and so on
goodmind/treact pull request #8
Opened 2017-01-09 08:41 UTC by zerobias

* Implemented mesage slice loading.
Use method api/chats loadSliceRange. It can load various slices ov history, helpful for continious history loading.

* Implemented redux fields chats (possibly should named as dialogs) and users
    *  *chats*. Main dialogs cache, reacts to slice loading, store every dialog messages in normalized form
    *  *users*. Draft realisation. Automatically updates if loaded slice contains unknown users.

* Implemented chat message component. "Dumb" message component also created in Chat folder, because it seems to me that in the future Chat component will become container, and its was better to debug when all child components was located in the same folder.

* Added Mtproto typings. Its really necessary when anybody will add typings to api actions, because almost all api actions begins with server response invoking.

* Moved complex thunk actions out from redux/modules. This dir contains sub-reducers composed to redux state. Possibly it should named
as redux/state or redux/reducers with current reducers.ts as index.ts file.

* Css styling helper classes in helpers/classes

* DC_SERVER env trim

2017-01-09 15:30 UTC, goodmind requested changes

2017-01-09 15:30 UTC, goodmind commented on src/app/helpers/Telegram/config.ts
> +import { trim } from 'lodash';
Change path to `lodash/trim`

2017-01-09 15:30 UTC, goodmind commented on src/app/helpers/Telegram/index.ts
> +    invoke<IMtpHelpGetConfig>('help.getConfig'),
What about something like this? https://goo.gl/JmBEwO

2017-01-09 15:30 UTC, goodmind commented on src/app/redux/api/auth.ts
> +import { invoke, APP_HASH, APP_ID, makePasswordHash } from 'helpers/Telegram';
Why this in `api/auth` folder? Why just don't leave it in `modules/auth` but rename to `actions.ts` or something like this?

2017-01-09 15:30 UTC, goodmind commented on src/app/redux/modules/messages/index.ts
> +    invoke<IMtpMessagesSlice>('messages.getHistory', {
Again https://goo.gl/JmBEwO

2017-01-09 15:30 UTC, goodmind commented on src/app/redux/modules/users.ts
> +// const byId =
Where is users?

2017-01-09 17:09 UTC, zerobias commented on src/app/redux/api/auth.ts
> +import { invoke, APP_HASH, APP_ID, makePasswordHash } from 'helpers/Telegram';
api folder is going to be huge, really bigger than modules folder itself. I don`t know where is should be, but now modules folder seems to be pure store implemenation directory

2017-01-14 10:54 UTC, goodmind requested changes
not ok

2017-01-14 10:54 UTC, goodmind commented on src/app/components/Message/index.tsx
Why not in `Components/Chat/Message`

2017-01-14 10:54 UTC, goodmind commented on src/app/helpers/state.ts
> +export const changeReducer = <G>(transformer: ITransformer) =>
Weird helper...

2017-01-14 10:54 UTC, goodmind commented on src/app/redux/modules/dialogs.ts
> +const byId = createReducer({
`createReducer` have type param which represents state

2017-01-14 10:54 UTC, goodmind commented on src/app/redux/modules/dialogs.ts
> +const reducer = combineReducers({
Also generic type param

2017-01-14 10:54 UTC, goodmind commented on src/app/redux/modules/loadings.ts
> +const setTrue = () => true;
Inconsistent with auth, also `ramda` has `R.T` and `R.F`

2017-01-14 10:54 UTC, goodmind commented on src/app/redux/api/histories.ts
> +      const pure = rejectDashAndFuncs(slice);
Why this isn't in `invoke` ?

2017-01-14 10:54 UTC, goodmind commented on src/app/redux/modules/chatList/index.ts
> -const saveConversation = (c, m) => dialog => {
miss

2017-01-14 10:54 UTC, goodmind commented on src/app/redux/api/chatList.ts
>  import { CHATS } from 'actions';
Why `api/histories` mixed with `api/dialogs`?

2017-01-15 11:45 UTC, goodmind commented
Roadmap Updates

- [ ] Mapped MTProto types
- [ ] R.T and R.F
- [ ] https://goo.gl/JmBEwO

2017-01-15 11:45 UTC, merged

2017-01-15 11:47 UTC, zerobias commented
R.T and R.F are already implemented at https://github.com/goodmind/treact/pull/8/commits/d4e73154617f49a1b16974b6a0d2ff4a0b5428c5